# `config.yml` is the place to store your configuration.
#
# Simply copy `config.sample.yml` to `config.yml` to get started.
# Customize to your neeeds. Overwrite the default vars of roles.
# Hint `config.yml` is excluded from the git repository by .gitignore.


# The dotfile role is skipped until your dotfiles_repository is defined. 
# dotfiles_repository: https://github.com/your-name/dotfiles.git  

gems:
  - tmuxinator

npms:
  - bower
  - grunt
  - grunt-cli

homebrew_taps:
  - homebrew/php
  - homebrew/dupes

homebrew_packages: 
  - tmux
  - vim
  - vimpager
  - docker
  - docker-compose

homebrew_casks:
  - alfred
  - firefox
  - google-chrome
  - virtualbox
  - vagrant
      
# Casks that need admin priviledges
homebrew_casks_become: []

homebrew_completions:
  - aptly-completion
  - boom-completion
  - boot2docker-completion
  - bundler-completion
  - ctest-completion
  - django-completion
  - docker-completion
  - fabric-completion
  - gem-completion
  - grunt-completion
  - kitchen-completion
  - maven-completion
  - packer-completion
  - pip-completion
  - rails-completion
  - rake-completion
  - ruby-completion
  - rustc-completion
  - sonar-completion
  - spring-completion
  - tmuxinator-completion
  - vagrant-completion
  - wpcli-completion

