---

- name: Me Playbook
  hosts: localhost
  roles:
    - bootstrap
    - software
    - role: dotfiles
      when: dotfiles_repository is defined
      tags: dotfiles
    - role: private
      tags: private

