
- name: Update and upgrade Homebrew
  homebrew: update_homebrew=yes upgrade_all=yes

- name: Maintain Ansible
  homebrew: name=ansible

- name: Maintain Bash
  homebrew: name=bash

- name: Maintain some Commandline Tools 
  homebrew: name=wget

- name: Maintain Python 
  homebrew: name=python

- name: Maintain Ruby 
  homebrew: name=ruby

- name: Maintain Iterm2 
  homebrew_cask: name=iterm2

- name: Maintain Tmux 
  homebrew: name=tmux

- name: Maintain Tmuxinator 
  gem: name=tmuxinator

- name: Maintain Vim 
  homebrew: name=vim,vimpager

- name: Maintain Git
  homebrew: name=git

- name: Maintain VirtualBox 
  homebrew_cask: name=virtualbox

- name: Maintain Vagrant 
  homebrew_cask: name=vagrant

- name: Maintain Docker
  homebrew: name=docker,docker-compose

- name: Maintain Chrome
  homebrew_cask: name=google-chrome

- name: Tap Completions
  homebrew_tap: tap=homebrew/completions 

- name: Maintain Completions
  homebrew: name="bash-completion,bundler-completion,docker-completion,gem-completion,grunt-completion,pip-completion,rake-completion,ruby-completion,tmuxinator-completion,vagrant-completion"

